name: Build Any Wheel

#on:
#  push:
#    branches:
#      - main
#      - 'releases/**'

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: python version
        run: python -m pip wheel .

      - uses: actions/upload-artifact@v3
        with:
          path: ./onnx_array_api*.whl
